name: pytest

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Download Archipelago
        run: wget https://github.com/ArchipelagoMW/Archipelago/releases/download/0.6.0/Archipelago_0.6.0_linux-x86_64.tar.gz -O arch.tar.gz
      - name: Extract Archipelago
        uses: ihiroky/extract-action@v1
        with:
          file_path: arch.tar.gz
      - name: Copy to path
        run: cp -r Archipelago/ /opt/
      - name: debug print path
        run: ls Archipelago
      - name: debug print path opt
        run: ls /opt/
      - name: Add ArchipelagoServer to path
        run: echo "export PATH=\$PATH:/opt/" >> $GITHUB_ENV
      - name: Run tests
        run: scripts/run_coverage.sh "Coverage for ${{ github.sha }}"
      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
          include-hidden-files: true
